### ISSUE TITLE
Im getting an error

### ISSUE THREAD

**Issue by BySuspect** [lavalink-devs/Lavalink#974] opened 2023-10-23 18:03 UTC
I bought a virtual machine and installed everything I needed to install. My discord bot works fine, but when it connects to lavalink, it gives an error and does not work for some reason. (trying on windows server 2019)

Log:
```
2023-10-23 20:53:55.459  INFO 5044 --- [           main] o.s.boot.SpringApplication               :
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)


2023-10-23 20:53:55.582  INFO 5044 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 17.0.9 on WIN-0P4LPA78TI7 with PID 5044 (C:\Users\Administrator\Desktop\lavalink\Lavalink.jar started by Administrator in C:\Users\Administrator\Desktop\lavalink)
2023-10-23 20:53:55.582  INFO 5044 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-10-23 20:53:56.705  INFO 5044 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.951 seconds (JVM running for 6.629)
2023-10-23 20:53:56.705  INFO 5044 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/lavalink-devs/Lavalink/issues/295
2023-10-23 20:53:56.782  INFO 5044 --- [           main] lavalink.server.Launcher                 :

[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

        Version:        3.7.8
        Build time:     03.08.2023 15:46:57 UTC
        Branch          HEAD
        Commit:         439f122
        Commit time:    03.08.2023 15:32:39 UTC
        JVM:            17.0.9
        Lavaplayer      1.5.0

2023-10-23 20:53:56.782  INFO 5044 --- [           main] o.s.boot.SpringApplication               :
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)


2023-10-23 20:53:56.798  INFO 5044 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-10-23 20:53:57.813  WARN 5044 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-10-23 20:53:57.844  INFO 5044 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-10-23 20:53:57.844  INFO 5044 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1046 ms
2023-10-23 20:53:58.016  INFO 5044 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2023-10-23 20:53:59.171  INFO 5044 --- [           main] lavalink.server.config.KoeConfiguration  : OS: WINDOWS, Arch: X86_64
2023-10-23 20:53:59.171  INFO 5044 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2023-10-23 20:53:59.187  INFO 5044 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2023-10-23 20:53:59.187  INFO 5044 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2023-10-23 20:53:59.280  WARN 5044 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2023-10-23 20:53:59.593  INFO 5044 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2023-10-23 20:53:59.609  INFO 5044 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2023-10-23 20:53:59.624  INFO 5044 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2023-10-23 20:53:59.749  INFO 5044 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2023-10-23 20:53:59.796  INFO 5044 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 2333 (http)
2023-10-23 20:53:59.811  INFO 5044 --- [           main] lavalink.server.Launcher                 : Started Launcher in 3.097 seconds (JVM running for 9.74)
2023-10-23 20:53:59.811  INFO 5044 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2023-10-23 20:54:00.155  INFO 5044 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-10-23 20:54:00.170  INFO 5044 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-10-23 20:54:00.170  INFO 5044 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
2023-10-23 20:54:00.202  INFO 5044 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:49693
2023-10-23 20:54:00.505  INFO 5044 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2023-10-23 20:54:00.719  WARN 5044 --- [pool-2-thread-1] o.u.p.windows.PerfCounterWildcardQuery   : Disabling further attempts to query Processor Information.
2023-10-23 20:54:01.607  WARN 5044 --- [pool-2-thread-1] o.u.p.windows.PerfCounterWildcardQuery   : Disabling further attempts to query Process.
2023-10-23 20:54:01.623  WARN 5044 --- [pool-2-thread-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Query: SELECT NAME,PRIORITY,CREATIONDATE,PROCESSID,PARENTPROCESSID,READTRANSFERCOUNT,WRITETRANSFERCOUNT,PRIVATEPAGECOUNT,PAGEFAULTSPERSEC FROM Win32_Process WHERE NOT Name LIKE"%_Total"
2023-10-23 20:54:01.656 ERROR 5044 --- [pool-2-thread-1] lavalink.server.io.StatsCollector        : Exception while sending stats

java.lang.NullPointerException: Cannot invoke "oshi.software.os.OSProcess.getKernelTime()" because "p" is null
        at lavalink.server.io.StatsCollector.getProcessRecentCpuUsage(StatsCollector.kt:58) ~[classes!/:na]
        at lavalink.server.io.StatsCollector.retrieveStats(StatsCollector.kt:106) ~[classes!/:na]
        at lavalink.server.io.StatsCollector.createTask$lambda$0(StatsCollector.kt:69) ~[classes!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]


```

**Comment by aikaterna** [comment] 2023-10-23 20:06
Looks like a duplicate of #858

**Comment by BySuspect** [comment] 2023-10-24 05:07
> Looks like a duplicate of #858

how can i fix this? 
this is a bug or something because its works fine on windows server 2012, i new upgraded to win server 2019 and its not working

**Comment by topi314** [comment] 2023-10-24 07:14
there is currently no fix for this, I recommend not to run Lavalink on windows

**Closed as not planned by topi314** 2023-10-24 07:14 UTC
