### ISSUE TITLE
there was an error while searching: This IP address has been blocked by YouTube (429).

### ISSUE THREAD

**Issue by vanna-code** [lavalink-devs/Lavalink#675] opened 2022-06-24 04:43 UTC
how to fix ? `there was an error while searching: This IP address has been blocked by YouTube (429).`

**Comment by Xirado** [comment] 2022-06-24 05:40
There is literally a [pinned issue](https://github.com/freyacodes/Lavalink/issues/369) about this...

**Comment by devoxin** [comment] 2022-06-24 08:51
Duplicate of #369

**Closed as not planned by devoxin** 2022-06-24 08:51 UTC
