### ISSUE TITLE
Lavalink wont login to google account. OAuth2 Fail.

### ISSUE THREAD

**Issue by Koekieezz** [lavalink-devs/Lavalink#910] opened 2023-07-09 10:01 UTC
## Description
![image](https://github.com/lavalink-devs/Lavalink/assets/112951868/79f10c77-b8af-4749-8828-598f1376727d)
Cant "login/auth" to google account

## To Reproduce
Just start the server and it wont do anything, cause i cant auth.

```
2023-07-09T16:58:18.024+07:00 ERROR 8864 --- [ForkJoinPool.commonPool-worker-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube master token update failed.

java.lang.RuntimeException: no identity in base-js found EID: 52bdb890-f536-4a06-9c2d-822326255a3b, js<redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:135) ~[lavaplayer-17c75f5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.extractIdentity(YoutubeAccessTokenTracker.java:410) ~[lavaplayer-17c75f5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchTVScript(YoutubeAccessTokenTracker.java:398) ~[lavaplayer-17c75f5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.exchangeOAuth2Token(YoutubeAccessTokenTracker.java:381) ~[lavaplayer-17c75f5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.continueUrl(YoutubeAccessTokenTracker.java:354) ~[lavaplayer-17c75f5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.requestMasterToken(YoutubeAccessTokenTracker.java:281) ~[lavaplayer-17c75f5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchMasterToken(YoutubeAccessTokenTracker.java:228) ~[lavaplayer-17c75f5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.lambda$updateMasterToken$0(YoutubeAccessTokenTracker.java:115) ~[lavaplayer-17c75f5.jar!/:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
```
## Expected behavior
Lavalink cant start to link with google account for youtube

## Version info
**Client used:** 4.0.0-Beta 1 and 3.7.6

Output of `java -version`:
```
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.2 (build 17.0.7+8-LTS-jvmci-22.3-b15)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.2 (build 17.0.7+8-LTS-jvmci-22.3-b15, mixed mode, sharing)
```

Lavalink Logs:
[spring.log](https://github.com/lavalink-devs/Lavalink/files/11994901/spring.log)

**Comment by freyacodes** [comment] 2023-07-09 10:19
Duplicate of #908

**Closed as not planned by freyacodes** 2023-07-09 10:19 UTC
Labels: lavaplayer issue
