### ISSUE TITLE
SoundCloud Broken

### ISSUE THREAD

**Issue by leoodz** [lavalink-devs/Lavalink#510] opened 2021-08-14 16:54 UTC
I'm using java 11

I tried dev version and newest master version but nothing work

**Comment by Sattishh** [comment] 2021-08-15 05:56
Hey, need to wait for lavaplayer to merge a pull request that fixes it issue

**Comment by kakarot-dev** [comment] 2021-08-15 06:40
And which pr are talking about?

**Comment by Sattishh** [comment] 2021-08-15 06:44
> And which pr are talking about?

Issue : https://github.com/sedmelluq/lavaplayer/issues/651
PR : https://github.com/sedmelluq/lavaplayer/pull/650

**Comment by leoodz** [comment] 2021-08-15 06:48
> > And which pr are talking about?
> 
> Issue : [sedmelluq/lavaplayer#651](https://github.com/sedmelluq/lavaplayer/issues/651)
> PR : [sedmelluq/lavaplayer#650](https://github.com/sedmelluq/lavaplayer/pull/650)

I run the lastest lavalink release and it give me this err when I tried to play a Soundcloud track, so it's a lavaplayer problem? and I can't do anything about it right?

**Comment by leoodz** [comment] 2021-08-15 07:07
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:43) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.78.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.78.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.78
  os.arch: amd64
  os.name: Linux
  os.version: 4.15.0-153-generic
  java.vendor: Ubuntu
  java.version: 11.0.11
  java.runtime.version: 11.0.11+9-Ubuntu-0ubuntu2.18.04
  java.vm.version: 11.0.11+9-Ubuntu-0ubuntu2.18.04
Caused by: java.lang.RuntimeException: No track JSON found EID: 58726f3a-d72a-4cf0-9fe4-cee8b2f89cf3, html <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134) ~[lavaplayer-1.3.78.jar!/:na]
        ... 11 common frames omitted

2021-08-15 07:04:22.058  INFO 10541 --- [  XNIO-1 task-4] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://soundcloud.com/i-n/beautiful-in-white-shayne-ward"
2021-08-15 07:04:22.912  WARN 10541 --- [ader-2-thread-1] c.s.d.lavaplayer.tools.ExceptionTools    : No track JSON found EID: 48372c4a-ca63-4af2-a10c-c091fada4869, html: <!DOCTYPE html>

**Comment by Sattishh** [comment] 2021-08-15 07:11
The issue is with lavaplayer so please be patient until the PR gets merged

**Closed as completed** 2021-08-15 07:18 UTC
