### ISSUE TITLE
Invalid status code for video page response: 400

### ISSUE THREAD

**Issue by BENx2115** [lavalink-devs/Lavalink#1012] opened 2024-02-19 18:59 UTC
## Description
Recently this error has been occurring more and more frequently
<h4>java.io.IOException: Invalid status code for video page response: 400</h4>
This error causes nothing to work for a few minutes (~ 10 min).

## To Reproduce
I've only been able to reproduce the error once so far
The error always occurs randomly during playback or during the search process for random songs.

## Version info
**Client used:** lavalink-client (v2.1.3)

Output of `java -version`:
```
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

Lavalink Logs:
```
2024-02-19T17:39:14.783+01:00 ERROR 1242 --- [lava-daemon-pool-playback-1-thread-541] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 5jQrBq6q3So

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.0.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 400
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:67) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.0.jar!/:na]
	... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 400
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:240) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-2.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-2.1.0.jar!/:na]
	... 7 common frames omitted

```

**Comment by NiceAesth** [comment] 2024-02-19 19:18
duplicate of https://github.com/lavalink-devs/lavaplayer/issues/69

**Comment by hmes98318** [comment] 2024-02-28 07:10
I'm not sure if this is the same error.  
Version: 3.7.10  

```
2024-02-28 15:01:54.313  INFO 75 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/dfis432wcgvd33i0/players/633980538767802368, client=127.0.0.1, payload={"encodedTrack":null}

2024-02-28 15:01:54.314  INFO 75 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:"JPJ221000176""

2024-02-28 15:01:54.472  INFO 75 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: "JPJ221000176"

2024-02-28 15:01:54.473  INFO 75 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/loadtracks?identifier=ytsearch%3A%22JPJ221000176%22, client=127.0.0.1

2024-02-28 15:01:54.476  INFO 75 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/dfis432wcgvd33i0/players/633980538767802368, client=127.0.0.1, payload={"encodedTrack":"QAAAdQIAEFdoZXJldmVyIHlvdSBhcmUAC09ORSBPSyBST0NLAAAAAAAEhEAAC2VvUUFuR3g0UHNzAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZW9RQW5HeDRQc3MAB3lvdXR1YmUAAAAAAAAAAA==","position":0}

2024-02-28 15:01:54.554 ERROR 75 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of eoQAnGx4Pss

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-1.5.2.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.2
  os.arch: amd64
  os.name: Linux
  os.version: 5.14.0-362.13.1.el9_3.x86_64
  java.vendor: Debian
  java.version: 17.0.9
  java.runtime.version: 17.0.9+9-Debian-1deb12u1
  java.vm.version: 17.0.9+9-Debian-1deb12u1
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 400
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:67) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:78) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-1.5.2.jar!/:na]
	... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 400
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:240) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-1.5.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-1.5.2.jar!/:na]
	... 7 common frames omitted
```

**Closed as not planned** 2024-02-29 07:47 UTC
Labels: bug

**Comment by kungkmg** [comment] 2024-11-17 02:12
help me for lavalink-4.0.8 error response: 400 

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.                                                           at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.2.jar!/:na]                                                                                                                                                       at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]                                               at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.io.IOException: Invalid status code for player api response: 400                                                                            at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.2.2.jar!/:na]        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadJsonResponse(NonMusicClient.java:67) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:107) ~[youtube-plugin-1.8.3.jar!/:na]        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35) ~[youtube-plugin-1.8.3.jar!/:na]                                                                                                                                                          at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:193) ~[youtube-plugin-1.8.3.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:119) ~[youtube-plugin-1.8.3.jar!/:na]                      at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[youtube-plugin-1.8.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]                                                                                                                                                       ... 4 common frames omitted
