### ISSUE TITLE
Add some kind of thumbmail/artwork property to rest api for tracks.

### ISSUE THREAD

**Issue by MrJacz** [lavalink-devs/Lavalink#183] opened 2019-03-28 13:53 UTC
I would like to see a thumbnail/artwork property for songs from the rest api. I feel like this would be useful for a lot of bots. most providers have a thumbnail

**Comment by devoxin** [comment] 2019-03-29 14:57
Duplicate of #160

**Closed as completed** 2019-05-06 21:10 UTC
